info:
  contact: {}
paths:
  /api/v1/book:
    get:
      consumes:
      - '*/*'
      description: Get book list from server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Book List.
      tags:
      - Books
swagger: "2.0"
